headless_track_generator:
  ros__parameters:
    component_data_straight: 1.0
    component_data_constant_turn: 0.7
    component_data_hairpin_turn: 0.3
    
    generator_values_min_straight: 35.0
    generator_values_max_straight: 75.0
    generator_values_min_constant_turn: 15.0
    generator_values_max_constant_turn: 20.0
    generator_values_min_hairpin: 10.0
    generator_values_max_hairpin: 20.0
    generator_values_max_hairpin_pairs: 2
    generator_values_max_length: 1000.0
    generator_values_max_length_variation: 350.0  # total range of random variation
    generator_values_lax_generation: False
    generator_values_track_width: 2.5

    num_tracks_to_generate: 10

    # Append to report.json the information about tracks which were generated.
    write_report: True
    report_filename: report.json
